# Generated by Django 5.1.4 on 2025-07-02 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='medecins',
        ),
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels', to='app.service'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Médecin', 'Médecin'), ('Infirmier', 'Infirmier'), ('Secrétaire', 'Secrétaire'), ('Administrateur', 'Administrateur'), ('Autre', 'Autre')], max_length=20),
        ),
    ]
