# Generated by Django 5.1.4 on 2025-07-03 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('motif', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('Confirmé', 'Confirmé'), ('Annulé', 'Annulé'), ('En attente', 'En attente')], default='En attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(blank=True, limit_choices_to={'role': 'Médecin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='app.patient')),
            ],
        ),
    ]
