# Generated by Django 5.1.4 on 2025-07-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='traitements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
