# Generated by Django 5.1.4 on 2025-07-03 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_patient_traitements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField()),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('code_maladie', models.CharField(blank=True, max_length=50, null=True)),
                ('conseils', models.TextField(blank=True, null=True)),
                ('recommandations', models.TextField(blank=True, null=True)),
                ('prochain_rdv', models.DateField(blank=True, null=True)),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentsMedicaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypertension', models.BooleanField(default=False)),
                ('diabete', models.BooleanField(default=False)),
                ('hypercholesterolemie', models.BooleanField(default=False)),
                ('infarctus', models.BooleanField(default=False)),
                ('avc', models.BooleanField(default=False)),
                ('fibrillation_auriculaire', models.BooleanField(default=False)),
                ('insuffisance_cardiaque', models.BooleanField(default=False)),
                ('autres', models.TextField(blank=True, null=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentsFamiliaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maladies_cardiaques', models.TextField(blank=True, null=True)),
                ('deces_precoces', models.TextField(blank=True, null=True)),
                ('autres', models.TextField(blank=True, null=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(max_length=100)),
                ('resultat', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('frequence', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='ModeDeVie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fumeur', models.BooleanField(default=False)),
                ('nombre_cigarettes', models.IntegerField(blank=True, null=True)),
                ('ancien_fumeur', models.BooleanField(default=False)),
                ('alcool', models.CharField(choices=[('jamais', 'Jamais'), ('occasionnellement', 'Occasionnellement'), ('souvent', 'Souvent')], default='jamais', max_length=50)),
                ('activite_physique', models.CharField(choices=[('sedentaire', 'Sédentaire'), ('moderee', 'Modérée'), ('active', 'Active')], default='sedentaire', max_length=50)),
                ('alimentation', models.CharField(choices=[('equilibree', 'Équilibrée'), ('deséquilibrée', 'Déséquilibrée')], default='equilibree', max_length=50)),
                ('stress', models.IntegerField(default=5)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='SignesVitaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tension_systolique', models.IntegerField(blank=True, null=True)),
                ('tension_diastolique', models.IntegerField(blank=True, null=True)),
                ('frequence_cardiaque', models.IntegerField(blank=True, null=True)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('saturation_o2', models.FloatField(blank=True, null=True)),
                ('glycemie', models.FloatField(blank=True, null=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Symptomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('douleur_thoracique', models.BooleanField(default=False)),
                ('essoufflement', models.BooleanField(default=False)),
                ('palpitations', models.BooleanField(default=False)),
                ('vertiges', models.BooleanField(default=False)),
                ('fatigue', models.BooleanField(default=False)),
                ('oedemes', models.BooleanField(default=False)),
                ('syncope', models.BooleanField(default=False)),
                ('autres', models.TextField(blank=True, null=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.consultation')),
            ],
        ),
    ]
