# Generated by Django 5.1.4 on 2025-07-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_consultation_antecedentsmedicaux_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='consultation',
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('recommandations', models.TextField(blank=True, null=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='app.consultation')),
            ],
        ),
        migrations.AddField(
            model_name='medicament',
            name='ordonnance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='app.ordonnance'),
        ),
    ]
