# Generated by Django 5.1.3 on 2025-07-11 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_medicament_consultation_ordonnance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('tension', models.CharField(blank=True, max_length=20, null=True)),
                ('pouls', models.IntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantes', to='app.patient')),
            ],
        ),
    ]
