# Generated by Django 5.1.3 on 2025-07-13 13:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_constante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstantesInfirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('tension_systolique', models.IntegerField(blank=True, null=True)),
                ('tension_diastolique', models.IntegerField(blank=True, null=True)),
                ('pouls', models.IntegerField(blank=True, null=True)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantes', to='app.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Constante',
        ),
    ]
