# Generated by Django 5.1.3 on 2025-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_constantesinfirmier_delete_constante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Médecin', 'Médecin'), ('Infirmier', 'Infirmier'), ('Secrétaire', 'Secrétaire'), ('Administrateur', 'Administrateur'), ('Patient', 'Patient'), ('Autre', 'Autre')], max_length=20),
        ),
    ]
