# Generated by Django 5.1.3 on 2025-07-13 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
