# Generated by Django 5.1.4 on 2025-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_patient_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confirmé', 'Confirmé'), ('Terminé', 'Terminé')], default='Confirmé', max_length=20),
        ),
    ]
