# Generated by Django 5.1.3 on 2025-07-17 19:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='est_validee',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=100)),
                ('frequence', models.CharField(max_length=100)),
                ('date_execution', models.DateField()),
                ('heure_execution', models.TimeField(default=datetime.time(8, 0))),
                ('est_effectuee', models.BooleanField(default=False)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ordonnance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
