# Generated by Django 5.1.3 on 2025-07-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_ordonnance_est_validee_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
